<?php
/**
 * Copyright (c) anno Domini nostri Jesu Christi MMXXIV John Boehr & contributors
 *
 * SPDX-License-Identifier: AGPL-3.0-only WITH romic-exception
 *
 * This file is generated by tools/generate-aggregate-stub.php from the canonical
 * platform declarations in stubs/. Do not edit it directly.
 */

namespace Perfidious;

/** @var bool Whether the extension was built with its debug-only test hooks. */
const DEBUG = false;

const VERSION = "0.3.0";

const MOTD = "Think not that I am come to send peace on earth: I came not to send peace, but a sword. Matthew 10:34";

interface ExceptionInterface
{
}

final class IOException extends \RuntimeException implements ExceptionInterface
{
}

final class ClosedException extends \LogicException implements ExceptionInterface
{
}

final class WrongThreadException extends \LogicException implements ExceptionInterface
{
}

final class ResourceBusyException extends \RuntimeException implements ExceptionInterface
{
}

final class OverflowException extends \OverflowException implements ExceptionInterface
{
}

final class PmuNotFoundException extends \InvalidArgumentException implements ExceptionInterface
{
}

final class PmuEventNotFoundException extends \InvalidArgumentException implements ExceptionInterface
{
}

final class UnsupportedMetricException extends \RuntimeException implements ExceptionInterface
{
    private function __construct()
    {
    }

    public readonly Scope $scope;

    /** @var non-empty-list<Metric> */
    public readonly array $unsupportedMetrics;
}

enum Scope: string
{
    case CurrentProcess = 'current-process';
    case CurrentThread = 'current-thread';
}

enum MetricUnit
{
    case Nanoseconds;
    case Count;
}

enum Metric: string
{
    case CpuTime = 'cpu-time';
    case PageFaults = 'page-faults';
    case ContextSwitches = 'context-switches';
    case CpuCycles = 'cpu-cycles';
    case Instructions = 'instructions';

    public function unit(): MetricUnit
    {
    }
}

final class Sampler
{
    private function __construct()
    {
    }

    /**
     * @phpstan-param non-empty-list<Metric> $metrics
     * @throws UnsupportedMetricException|ResourceBusyException|IOException|OverflowException
     */
    public static function open(array $metrics, Scope $scope = Scope::CurrentThread): Sampler
    {
    }

    /** @phpstan-return non-empty-list<Metric> */
    public function metrics(): array
    {
    }

    /** @throws ClosedException|WrongThreadException|IOException|OverflowException */
    public function read(): Sample
    {
    }

    public function close(): void
    {
    }
}

final class Sample
{
    private function __construct()
    {
    }

    public function value(Metric $metric): int
    {
    }

    public function since(Sample $earlier): SampleDelta
    {
    }
}

final class SampleDelta
{
    private function __construct()
    {
    }

    public readonly int $elapsedTimeNs;

    public function value(Metric $metric): int
    {
    }
}

/**
 * @phpstan-template T of list<string>
 */
final class ReadResult
{
    /** Total nanoseconds enabled over the handle's lifetime, including before reset(). */
    public readonly int $timeEnabled;
    /** Total nanoseconds running over the handle's lifetime, including before reset(). */
    public readonly int $timeRunning;
    /**
     * @var array<string, int>
     * @phpstan-var array<value-of<T>, int>
     */
    public readonly array $values;
}

namespace Perfidious;

/**
 * @throws PmuNotFoundException
 * @see https://perfmon2.sourceforge.net/manv4/pfm_get_pmu_info.html
 */
function get_pmu_info(int $pmu): PmuInfo
{
}

/**
 * The event index must belong to the requested PMU.
 *
 * @throws PmuNotFoundException|PmuEventNotFoundException
 * @see https://perfmon2.sourceforge.net/manv4/pfm_get_event_info.html
 */
function get_pmu_event_info(int $pmu, int $idx): PmuEventInfo
{
}

/**
 * @phpstan-return list<PmuInfo>
 * @see https://perfmon2.sourceforge.net/manv4/pfm_get_pmu_info.html
 */
function list_pmus(): array
{
}

/**
 * @phpstan-return list<PmuEventInfo>
 * @throws PmuNotFoundException|PmuEventNotFoundException
 * @see https://perfmon2.sourceforge.net/manv4/pfm_get_event_info.html
 */
function list_pmu_events(int $pmu): array
{
}

/**
 * @param array $event_names a list of libpfm event names, see list_pmu_events
 * @param int $pid process/thread selector, which must fit the native PID type
 * @param int $cpu -1 or a nonnegative CPU ID that fits a native int, with availability checked by the kernel
 * @throws PmuEventNotFoundException|IOException|OverflowException|\ValueError
 *
 * @phpstan-template T of string
 * @phpstan-param list<T> $event_names
 * @phpstan-return Handle<list<T>>
 */
function open(array $event_names, int $pid = 0, int $cpu = -1): Handle
{
}

/**
 * Returns a borrowed view of the request handle, initialized on the worker's first request.
 * Closing the returned object detaches only that view.
 *
 * Initialization is retried on later requests if opening fails. Pending initialization or
 * lifecycle errors are thrown once when this function is called; subsequent calls return
 * null if the handle is unavailable for this request.
 * An unconsumed error remains pending even if a later request successfully opens the handle.
 * @throws PmuEventNotFoundException|IOException if the handle could not be prepared
 * @phpstan-return ?Handle<list<string>>
 */
function request_handle(): ?Handle
{
}

/**
 * Handles returned by open() own their native descriptors and release them on close() or destruction.
 * Handles returned by request_handle() are borrowed views of persistent native state.
 *
 * @phpstan-template T of list<string>
 */
final class Handle
{
    /**
     * Releases owned descriptors immediately or detaches this borrowed view.
     * This method is idempotent; every other method throws ClosedException after it is called.
     *
     * @throws IOException
     */
    final public function close(): void
    {
    }

    /**
     * @phpstan-return $this
     * @throws ClosedException|IOException
     */
    final public function enable(): Handle
    {
    }

    /**
     * @phpstan-return $this
     * @throws ClosedException|IOException
     */
    final public function disable(): Handle
    {
    }

    /**
     * Get a raw byte stream backed by a duplicate of one of the handle's file descriptors.
     *
     * Index 0 is the event-group leader; requested events begin at index 1 in request order.
     * @note the returned stream owns an independent copy of the file descriptor, so closing it
     *       does not affect this handle or subsequent calls to read()
     * @return resource
     * @throws ClosedException|IOException
     * @throws \ValueError if idx does not reference an existing file descriptor
     */
    final public function rawStream(int $idx = 0)
    {
    }

    /**
     * Returns raw counts since opening or the latest reset, with kernel-lifetime timing totals.
     *
     * @throws ClosedException|OverflowException|IOException
     *
     * @phpstan-return ReadResult<T>
     */
    final public function read(): ReadResult
    {
    }

    /**
     * @throws ClosedException|OverflowException|IOException
     *
     * @phpstan-return array<value-of<T>, int>
     */
    final public function readArray(): array
    {
    }

    /**
     * Clears counts while preserving the enabled state. Lifetime timing totals are not cleared.
     * Active counters are briefly disabled to capture the timing baseline used by phpinfo().
     *
     * @phpstan-return $this
     * @throws ClosedException|IOException
     */
    final public function reset(): Handle
    {
    }
}

/**
 * @see https://perfmon2.sourceforge.net/manv4/pfm_get_pmu_info.html
 */
final class PmuInfo
{
    /**
     * Symbolic PMU name, usable as an event-string prefix.
     */
    public readonly string $name;
    public readonly string $desc;
    /**
     * Unique PMU identifier, matching the requested $pmu in get_pmu_info().
     */
    public readonly int $pmu;
    public readonly int $type;
    /**
     * Number of available events for this PMU model on the host; valid only when $is_present is true.
     */
    public readonly int $nevents;
    /**
     * Whether this PMU model was detected on the host.
     */
    public readonly bool $is_present;
}

/**
 * @see https://perfmon2.sourceforge.net/manv4/pfm_get_event_info.html
 */
final class PmuEventInfo
{
    public readonly string $name;
    public readonly string $desc;
    /**
     * Complete equivalent event string for shortcut events, when provided; otherwise null.
     */
    public readonly ?string $equiv;
    /**
     * Identifier of the PMU model that owns this event.
     */
    public readonly int $pmu;
    /**
     * Libpfm event index for get_pmu_event_info().
     */
    public readonly int $idx;
    /**
     * Whether this PMU model was detected on the host.
     */
    public readonly bool $is_present;
}

namespace Perfidious\Darwin;

/**
 * Return cumulative resource usage for the current process.
 *
 * CPU times are reported in nanoseconds. Hardware cycle and instruction counts may be zero when
 * the kernel cannot collect them, including on some virtualized systems.
 *
 * @throws \Perfidious\IOException|\Perfidious\OverflowException
 * @see https://developer.apple.com/documentation/kernel/rusage_info_v4
 */
function get_current_process_resource_usage(): ProcessResourceUsage
{
}

/**
 * Return cumulative resource usage for the current thread.
 *
 * CPU times are reported in nanoseconds. Hardware cycle and instruction counts may be zero when
 * the kernel cannot collect them, including on macOS before 12.4 and on some virtualized systems.
 *
 * @throws \Perfidious\IOException|\Perfidious\OverflowException
 * @see https://github.com/apple-oss-distributions/xnu/blob/main/bsd/sys/resource_private.h
 */
function get_current_thread_resource_usage(): ThreadResourceUsage
{
}

final class ProcessResourceUsage
{
    private function __construct()
    {
    }

    public readonly int $userTimeNs;
    public readonly int $systemTimeNs;
    public readonly int $minorPageFaultCount;
    public readonly int $majorPageFaultCount;
    public readonly int $voluntaryContextSwitchCount;
    public readonly int $involuntaryContextSwitchCount;
    public readonly int $instructionCount;
    public readonly int $cycleCount;
}

final class ThreadResourceUsage
{
    private function __construct()
    {
    }

    public readonly int $userTimeNs;
    public readonly int $systemTimeNs;
    public readonly int $instructionCount;
    public readonly int $cycleCount;
}

namespace Perfidious\Windows;

/**
 * Return the current process's cumulative CPU cycle count.
 *
 * @throws \Perfidious\IOException|\Perfidious\OverflowException
 * @see https://learn.microsoft.com/en-us/windows/win32/api/realtimeapiset/nf-realtimeapiset-queryprocesscycletime
 */
function query_current_process_cycle_time(): int
{
}

/**
 * Return the current thread's cumulative CPU cycle count.
 *
 * @throws \Perfidious\IOException|\Perfidious\OverflowException
 * @see https://learn.microsoft.com/en-us/windows/win32/api/realtimeapiset/nf-realtimeapiset-querythreadcycletime
 */
function query_current_thread_cycle_time(): int
{
}

/**
 * Return timing information for the current process.
 *
 * @throws \Perfidious\IOException|\Perfidious\OverflowException
 * @see https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getprocesstimes
 */
function get_current_process_times(): ProcessTimes
{
}

/**
 * Return timing information for the current thread.
 *
 * The native exit timestamp is omitted because the current thread is necessarily still running.
 *
 * @throws \Perfidious\IOException|\Perfidious\OverflowException
 * @see https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getthreadtimes
 */
function get_current_thread_times(): ThreadTimes
{
}

/**
 * Return PROCESS_MEMORY_COUNTERS_EX values for the current process. Memory sizes are in bytes.
 * @throws \Perfidious\IOException|\Perfidious\OverflowException
 * @see https://learn.microsoft.com/en-us/windows/win32/api/psapi/nf-psapi-getprocessmemoryinfo
 */
function get_current_process_memory_info(): ProcessMemoryInfo
{
}

/**
 * Enable profiling for the current thread.
 *
 * Hardware counters are a bitmask of up to 16 globally configured counter indices. Configuring
 * those counters requires a kernel driver; an unconfigured requested counter reads as zero.
 *
 * @throws \Perfidious\ResourceBusyException|\Perfidious\IOException
 * @see https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-enablethreadprofiling
 */
function enable_current_thread_profiling(int $hardwareCounterMask = 0): ThreadProfile
{
}

final class ProcessTimes
{
    private function __construct()
    {
    }

    /**
     * The process creation timestamp as 100-nanosecond intervals since January 1, 1601 UTC.
     */
    public readonly int $creationTimeFiletime;

    /**
     * Time spent by the process in kernel mode, in 100-nanosecond units.
     */
    public readonly int $kernelTime100ns;

    /**
     * Time spent by the process in user mode, in 100-nanosecond units.
     */
    public readonly int $userTime100ns;
}

final class ThreadTimes
{
    private function __construct()
    {
    }

    /**
     * The thread creation timestamp as 100-nanosecond intervals since January 1, 1601 UTC.
     */
    public readonly int $creationTimeFiletime;

    /**
     * Time spent by the thread in kernel mode, in 100-nanosecond units.
     */
    public readonly int $kernelTime100ns;

    /**
     * Time spent by the thread in user mode, in 100-nanosecond units.
     */
    public readonly int $userTime100ns;
}

final class ProcessMemoryInfo
{
    private function __construct()
    {
    }

    public readonly int $pageFaultCount;
    public readonly int $peakWorkingSetSize;
    public readonly int $workingSetSize;
    public readonly int $quotaPeakPagedPoolUsage;
    public readonly int $quotaPagedPoolUsage;
    public readonly int $quotaPeakNonPagedPoolUsage;
    public readonly int $quotaNonPagedPoolUsage;

    /**
     * The process commit charge in bytes; retained under the native PROCESS_MEMORY_COUNTERS_EX field name.
     */
    public readonly int $pagefileUsage;

    /**
     * The peak process commit charge in bytes; retained under the native PROCESS_MEMORY_COUNTERS_EX field name.
     */
    public readonly int $peakPagefileUsage;

    /**
     * The process's private committed memory in bytes.
     */
    public readonly int $privateUsage;
}

final class HardwareCounterSnapshot
{
    private function __construct()
    {
    }

    public readonly int $index;
    public readonly int $type;
    public readonly int $value;
}

final class ThreadProfileSnapshot
{
    private function __construct()
    {
    }

    /**
     * Context switches since profiling was enabled.
     */
    public readonly int $contextSwitchCount;

    /**
     * Wait reasons observed since the previous native read, encoded as a fixed-width hexadecimal bitmap.
     */
    public readonly string $waitReasonBitmapHex;

    /**
     * CPU cycles since the profiler's initial baseline sample.
     */
    public readonly int $cycleCount;

    /**
     * Reads Windows needed to obtain this consistent snapshot.
     */
    public readonly int $readRetryCount;

    /**
     * Number of hardware-counter array elements Windows reports as populated.
     */
    public readonly int $hardwareCounterCount;

    /**
     * Every requested counter keyed by its globally configured index. A value of zero may mean either
     * no events occurred or the requested index was not configured.
     *
     * @var array<int, HardwareCounterSnapshot>
     */
    public readonly array $hardwareCounters;
}

final class ThreadProfile
{
    private function __construct()
    {
    }

    /**
     * @throws \Perfidious\ClosedException|\Perfidious\IOException|\Perfidious\OverflowException
     * @see https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-readthreadprofilingdata
     */
    final public function read(): ThreadProfileSnapshot
    {
    }

    /**
     * @throws \Perfidious\IOException
     */
    final public function close(): void
    {
    }
}
