<?php
/**
 * Copyright (c) anno Domini nostri Jesu Christi MMXXIV John Boehr & contributors
 *
 * SPDX-License-Identifier: AGPL-3.0-only WITH romic-exception
 */

/** @var list<string> $arguments */
$arguments = $_SERVER['argv'] ?? [];

(static function (array $arguments): void {
    $root = dirname(__DIR__);
    $output = <<<'PHP'
<?php
/**
 * Copyright (c) anno Domini nostri Jesu Christi MMXXIV John Boehr & contributors
 *
 * SPDX-License-Identifier: AGPL-3.0-only WITH romic-exception
 *
 * This file is generated by tools/generate-aggregate-stub.php from the canonical
 * platform declarations in stubs/. Do not edit it directly.
 */
PHP;

    foreach (['common', 'linux', 'darwin', 'windows'] as $platform) {
        $path = sprintf('%s/stubs/%s.stub.php', $root, $platform);
        $contents = file_get_contents($path);
        if ($contents === false) {
            throw new RuntimeException(sprintf('Could not read %s', $path));
        }

        $namespaceOffset = strpos($contents, "\nnamespace ");
        if ($namespaceOffset === false) {
            throw new RuntimeException(sprintf('Could not find namespace declaration in %s', $path));
        }

        $output .= "\n\n" . rtrim(substr($contents, $namespaceOffset + 1));
    }

    $output .= "\n";
    $target = $root . '/perfidious.stub.php';

    if (($arguments[1] ?? null) === '--check') {
        $actual = file_get_contents($target);
        if ($actual !== $output) {
            fwrite(STDERR, "perfidious.stub.php is not up to date; run tools/generate-aggregate-stub.php\n");
            exit(1);
        }

        exit(0);
    }

    if (count($arguments) !== 1) {
        fwrite(STDERR, "usage: tools/generate-aggregate-stub.php [--check]\n");
        exit(2);
    }

    if (file_put_contents($target, $output) === false) {
        throw new RuntimeException(sprintf('Could not write %s', $target));
    }
})($arguments);
